language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
node_js:
  - "lts/*"

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run lint
      env: lint
    - script: npm run test
      env: unit_test
    - script: npm run coveralls
      env: coverage
