language: node_js
sudo: false
cache:
  directories:
    - "node_modules"
node_js:
  - "lts/*"

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run lint
    - script: npm run test

after_success:
  - npm run coveralls
